version: "3.8"
services:
  gateway:
    build:
      context: ./apiGateway/
      dockerfile: Dockerfile.yml
    ports:
      - $PORTGATEWAY:3000
    command: npm start
    depends_on:
      - auth
    networks:
      - back

  auth:
    build:
      context: ./user/
      dockerfile: Dockerfile.yml
    ports:
      - $PORTAUTH:4001
    command: npm start
    depends_on:
      - mongodb1
    networks:
      - back

  blog:
    build:
      context: ./blog/
      dockerfile: Dockerfile.yml
    ports:
      - $PORTBLOG:4002
    command: npm start
    depends_on:
      - mongodb2
    networks:
      - back

  mongodb1:
    image: mongo:latest # use the latest image.
    container_name: mongodb1
    restart: unless-stopped
    # environment: # set required env variables to access mongo
    #   MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
    #   MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - $MONGO_PORTAUTH:27017
    volumes: # to preserve database after container is deleted.
      - ./database1-data:/data/db
    networks:
      - back

  mongodb2:
    image: mongo:latest # use the latest image.
    container_name: mongodb2
    restart: unless-stopped
    # environment: # set required env variables to access mongo
    #   MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
    #   MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - $MONGO_PORTBLOG:27017
    volumes: # to preserve database after container is deleted.
      - ./database2-data:/data/db
    networks:
      - back

  # Mongo Express Service
  # mongo-express:
  #   image: mongo-express:latest # latest image
  #   container_name: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - $MONGO_EXPRESS_PORT:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_EXPRESS_USER
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_EXPRESS_PASSWORD
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     # use the name of the mongo container above for server env var.
  #     # In our case this is mongodb
  #   networks:
  #     - back

networks:
  back:
    driver: bridge
